
#######################################
# Column Names

MATCH_ID = "Match ID"
PLAYER_ID = "Player ID"
RUNS_MADE = "Runs Made"
DISMISSED_COL = "Dismissed"
BALLS_BOWLED = "Balls Bowled"
WICKETS_COL = "Wickets Taken"
RUNS_GIVEN = "Runs Given"

RUN_AVG_COL = "Run_AVG"
RUNVALUE_COL = "RunValues"
RUNVALUE_AVG_COL = "RunValue_AVG"
BATTING_INNINGS_PLAYED = "Num_Bat_Innings"
BATTING_COMBINED_SCORE = "Batting_Combined_Score"

WICKETS_AVG_COL = "Wickets_AVG"
WICKETVALUE_COL = "WicketValues"
WICKETVALUE_AVG_COL = "WicketValue_AVG"
BOWLING_INNINGS_PLAYED = "Num_Bowl_Innings"
BOWLING_COMBINED_SCORE = "Bowling_Combined_Score"

BATTING_RANKING = "Batting_Ranking"
BOWLING_RANKING = "Bowling_Ranking"

#######################################
# T20 Ranking Aggregation Proportions

T20_MIN_NUM_BATTING_INNINGS = 5.0
T20_MIN_NUM_BOWLING_INNINGS = 5.0

T20_BATTING_RUNSVALUE_TOTAL_PROP = 60.0
T20_BATTING_RUNSVALUE_AVG_PROP = 40.0

T20_BOWLING_WICKETSVALUE_TOTAL_PROP = 60.0
T20_BOWLING_WICKETSVALUE_AVG_PROP = 40.0

T20_RUNS_MIN_PERCENTILE = 0.1
T20_RUNS_MAX_PERCENTILE = 0.95

T20_WICKETS_MIN_PERCENTILE = 0.2
T20_WICKETS_MAX_PERCENTILE = 0.95